In [2]:
import numpy as np

In [3]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [4]:
type(data)

numpy.ndarray

In [5]:
data.dtype

dtype('int64')

In [6]:
data.ndim

1

In [7]:
data.shape

(3,)

In [8]:
data.size

3

In [9]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [10]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [14]:
full = np.full(6,10)
full

array([10, 10, 10, 10, 10, 10])

In [20]:
np.diag((3, 3),0)

array([[3, 0],
       [0, 3]])

In [22]:
rand = np.random.random(3)
rand

array([0.1911726 , 0.57633494, 0.96057004])

In [26]:
rand = np.random.randint(5, size=3)
rand 

array([4, 4, 3])

In [27]:
rang = np.arange(0, 10)
rang

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ones + data

array([2., 3., 4.])

In [28]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [30]:
ones - data

array([ 0., -1., -2.])

In [31]:
ones * data

array([1., 2., 3.])

In [32]:
ones / data

array([1.        , 0.5       , 0.33333333])

In [48]:
ones

array([1., 1., 1.])

In [49]:
data

array([1, 2, 3])

In [33]:
v = np.vstack((data, ones)) 
v

array([[1., 2., 3.],
       [1., 1., 1.]])

In [35]:
h = np.hstack((v, v)) 
h

array([[1., 2., 3., 1., 2., 3.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
lst = [[1, 2],[3, 4]]
lst[1][1]

4

In [39]:
[b, c] = np.vsplit(v, 2)

In [40]:
c

array([[1., 1., 1.]])

In [42]:
ones * 2

array([2., 2., 2.])

In [47]:
np.mean(data)

2.0

In [52]:
lst = [[1, 2],[3, 4]]
lst[1][1]

4

In [69]:
data = np.array([[1,2],[3,4], [11, 12]])
data

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [64]:
data[1:,1:]

array([[ 4,  8],
       [12, 13]])

In [61]:
data.shape

(3, 3)

In [57]:
data[:,1]

array([2, 4])

In [70]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
rand = np.random.random((3, 2))
rand

array([[0.09393035, 0.46683805],
       [0.97335144, 0.62626771],
       [0.20904692, 0.37466938]])

In [71]:
data + ones

array([[ 2.,  3.],
       [ 4.,  5.],
       [12., 13.]])

In [72]:
rand.shape, ones.shape

((3, 2), (3, 2))

In [85]:
rand.shape, ones.T.shape

((3, 2), (2, 3))

In [103]:
result = rand.dot(ones.T)
result

array([[0.5607684 , 0.5607684 , 0.5607684 ],
       [1.59961915, 1.59961915, 1.59961915],
       [0.5837163 , 0.5837163 , 0.5837163 ]])

In [102]:
data
#data.max()

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [83]:
data.max(axis=1)

array([ 2,  4, 12])

In [98]:
result = result.reshape(9,1)
result.shape

(9, 1)

In [100]:
result = result.reshape(-1,)
result.shape

(9,)

In [101]:
result

array([0.5607684 , 0.5607684 , 0.5607684 , 1.59961915, 1.59961915,
       1.59961915, 0.5837163 , 0.5837163 , 0.5837163 ])

In [104]:
result

array([[0.5607684 , 0.5607684 , 0.5607684 ],
       [1.59961915, 1.59961915, 1.59961915],
       [0.5837163 , 0.5837163 , 0.5837163 ]])

In [114]:
con = result > 1.1
s = np.where(con, result, 10)
s

array([[10.        , 10.        , 10.        ],
       [ 1.59961915,  1.59961915,  1.59961915],
       [10.        , 10.        , 10.        ]])

In [115]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [117]:
predictions = np.random.random((3, 1))
predictions

array([[0.23610238],
       [0.7717362 ],
       [0.28229878]])

In [116]:
labels = np.random.random((3, 1))
labels

array([[0.73021603],
       [0.63364913],
       [0.14420255]])

In [125]:
# To do
n = labels.shape[0]
1/n * np.sum(np.square(predictions - labels))

0.09409563463474671